sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t akxrawatar/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true akxrawatar/react-test npm test

after_success:
  - docker build -t akxrawatar/multi-client ./client
  - docker build -t akxrawatar/multi-nginx ./nginx
  - docker build -t akxrawatar/multi-server ./server
  - docker build -t akxrawatar/multi-worker ./worker
  # log in to docker CLI by saving credentials to travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take these images and push them to docker hub
  - docker push akxrawatar/multi-client
  - docker push akxrawatar/multi-nginx
  - docker push akxrawatar/multi-server
  - docker push akxrawatar/multi-worker